# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[fr]
  languageCode = "fr"
  contentDir = "content/fr"
  title = "Kit de démarrage INOSC"
  [fr.params]
    description = "Ce kit de démarrage vous fournit les arguments, le modèle et les directives pour lancer votre propre Communauté science ouverte locale. Alors n'hésitez pas à vous lancer et vous mettre en relation avec nous."
  [[fr.menu.main]]
    name = "Kit de démarrage INOSC"
    url = "docs/"
    weight = 1
